"""test running migrations

Revision ID: 046b3df41b53
Revises: 7fa1987aaceb
Create Date: 2023-02-28 00:32:48.673104

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "046b3df41b53"
down_revision = "7fa1987aaceb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
