"""test running migrations

Revision ID: 0a92bde9008c
Revises: 046b3df41b53
Create Date: 2023-02-28 02:17:22.098782

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "0a92bde9008c"
down_revision = "046b3df41b53"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
