"""test running migrations

Revision ID: 33dc4fb062a6
Revises: f635d54a3359
Create Date: 2023-04-10 21:04:06.745974

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "33dc4fb062a6"
down_revision = "f635d54a3359"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
