"""test running migrations

Revision ID: 5e4018a6f744
Revises: c939997a8a87
Create Date: 2023-04-10 20:44:49.291918

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "5e4018a6f744"
down_revision = "c939997a8a87"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
