"""test running migrations

Revision ID: 7ad45ac4d92f
Revises: 5e4018a6f744
Create Date: 2023-04-10 20:47:09.522264

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7ad45ac4d92f"
down_revision = "5e4018a6f744"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
