"""test running migrations

Revision ID: 7fa1987aaceb
Revises: 7c978838c2fb
Create Date: 2023-02-27 23:45:08.440139

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "7fa1987aaceb"
down_revision = "7c978838c2fb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
