"""test running migrations

Revision ID: 94f0a3e9f8b7
Revises: 33dc4fb062a6
Create Date: 2023-04-10 21:05:17.427443

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "94f0a3e9f8b7"
down_revision = "33dc4fb062a6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
