"""test running migrations

Revision ID: f635d54a3359
Revises: 7ad45ac4d92f
Create Date: 2023-04-10 21:01:56.789177

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "f635d54a3359"
down_revision = "7ad45ac4d92f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
