"""test running migrations

Revision ID: f7bd7a1bf331
Revises: 7dc4cd113a62
Create Date: 2023-03-18 23:15:55.074934

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "f7bd7a1bf331"
down_revision = "7dc4cd113a62"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
